# Generated by Django 6.0.4 on 2026-05-09 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0004_alter_chapter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorEditorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_method', models.CharField(choices=[('editor_code', 'Author used editor invite code'), ('manual', 'Manually assigned by CE / admin'), ('auto', 'Auto-assigned by system')], default='editor_code', max_length=15)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_ae', models.ForeignKey(blank=True, limit_choices_to={'role': 'ae'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_authors', to=settings.AUTH_USER_MODEL)),
                ('author', models.OneToOneField(limit_choices_to={'role': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='editor_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'author_editor_links',
            },
        ),
        migrations.CreateModel(
            name='ChapterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ae_reviewing', 'AE Reviewing'), ('ae_approved', 'AE Approved'), ('ae_revision', 'AE Requested Revision'), ('ae_escalated', 'Escalated to SE'), ('se_reviewing', 'SE Reviewing'), ('se_approved', 'SE Approved'), ('se_revision', 'SE Requested Major Revision'), ('se_escalated', 'Escalated to CE'), ('ce_reviewing', 'CE Reviewing'), ('ce_approved', 'CE Approved'), ('ce_revision', 'CE Requested Revision'), ('removed', 'Content Removed'), ('author_suspended', 'Author Suspended')], db_index=True, default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pacing_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dialogue_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consistency_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_ae', models.ForeignKey(blank=True, limit_choices_to={'role': 'ae'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ae_reviews', to=settings.AUTH_USER_MODEL)),
                ('assigned_ce', models.ForeignKey(blank=True, limit_choices_to={'role': 'ce'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ce_reviews', to=settings.AUTH_USER_MODEL)),
                ('assigned_se', models.ForeignKey(blank=True, limit_choices_to={'role': 'se'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='se_reviews', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_submissions', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_reviews', to='chapters.chapter')),
            ],
            options={
                'db_table': 'chapter_reviews',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('mature', 'Mature Content'), ('violence', 'Violence'), ('plagiarism', 'Plagiarism'), ('quality', 'Quality / Style'), ('spam', 'Spam'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_flags', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='editorial.chapterreview')),
            ],
            options={
                'db_table': 'content_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('editor', models.OneToOneField(help_text='The AE or SE being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='editorial_assignment', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, help_text='SE supervising this AE — or CE supervising this SE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'editor_assignments',
            },
        ),
        migrations.CreateModel(
            name='EditorialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('style', 'Style Suggestion'), ('continuity', 'Continuity Issue'), ('policy', 'Policy Concern'), ('decision', 'Decision Record')], default='general', max_length=15)),
                ('content', models.TextField()),
                ('paragraph', models.PositiveSmallIntegerField(blank=True, help_text='Paragraph index the note refers to', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_notes', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='editorial.chapterreview')),
            ],
            options={
                'db_table': 'editorial_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under Review'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ce'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Editorial Policies',
                'db_table': 'editorial_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruling', models.CharField(choices=[('approve', 'Approved'), ('approve_age_gate', 'Approved with Age-Gate'), ('revision', 'Major Revision Required'), ('remove', 'Content Removed'), ('suspend_author', 'Author Suspended')], max_length=20)),
                ('reasoning', models.TextField()),
                ('sets_precedent', models.BooleanField(default=False, help_text='If true, this decision will be referenced in future policy guidance')),
                ('notified_se', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(limit_choices_to={'role': 'ce'}, on_delete=django.db.models.deletion.CASCADE, related_name='policy_decisions', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_decision', to='editorial.chapterreview')),
            ],
            options={
                'db_table': 'policy_decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chapterreview',
            index=models.Index(fields=['status', 'assigned_ae'], name='chapter_rev_status_ebe075_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterreview',
            index=models.Index(fields=['status', 'assigned_se'], name='chapter_rev_status_f1d6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterreview',
            index=models.Index(fields=['status', 'assigned_ce'], name='chapter_rev_status_3baec6_idx'),
        ),
    ]
