# Generated by Django 6.0.4 on 2026-05-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='One-time registration token sent to the invitee.', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email address the invite was sent to.', max_length=254)),
                ('role', models.CharField(choices=[('ae', 'Assistant Editor'), ('se', 'Senior Editor')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invite expires 7 days after creation.')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invite', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(help_text='The CE who created this invite.', on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, help_text='For AE invites: the SE they will report to. For SE invites: the CE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'editor_invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
