# Generated by Django 6.0.4 on 2026-05-12 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_chapter_reviewed_at_chapter_reviewed_by_se_and_more'),
        ('editorial', '0002_editorinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chapterreview',
            name='chapter_rev_status_ebe075_idx',
        ),
        migrations.RemoveIndex(
            model_name='chapterreview',
            name='chapter_rev_status_f1d6f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='chapterreview',
            name='chapter_rev_status_3baec6_idx',
        ),
        migrations.RemoveField(
            model_name='policydecision',
            name='review',
        ),
        migrations.RemoveField(
            model_name='contentflag',
            name='review',
        ),
        migrations.RemoveField(
            model_name='editorialnote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='editorialnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='policydecision',
            name='notified_se',
        ),
        migrations.AddField(
            model_name='authoreditorlink',
            name='assigned_se',
            field=models.ForeignKey(blank=True, help_text='Set directly when an SE recruits an author using their own code.', limit_choices_to={'role': 'se'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='editorialnote',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorial_notes', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='editorialnote',
            name='written_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='written_editorial_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydecision',
            name='chapter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_decision', to='chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='editorialnote',
            name='note_type',
            field=models.CharField(choices=[('general', 'General'), ('style', 'Style Suggestion'), ('continuity', 'Continuity Issue'), ('policy', 'Policy Concern')], default='general', max_length=15),
        ),
        migrations.AlterField(
            model_name='editorinvite',
            name='role',
            field=models.CharField(choices=[('ae', 'Acquisition Editor'), ('se', 'Senior Editor')], max_length=5),
        ),
        migrations.DeleteModel(
            name='ChapterReview',
        ),
    ]
