# Generated by Django 6.0.4 on 2026-05-13 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_remove_chapterreview_chapter_rev_status_ebe075_idx_and_more'),
        ('stories', '0004_story_contract_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('se_reviewing', 'SE Reviewing'), ('se_approved', 'SE Approved'), ('rejected', 'Rejected'), ('contract_sent', 'Contract Sent'), ('signed', 'Signed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('se_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('se_note', models.TextField(blank=True)),
                ('contract_sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('exclusive', 'Exclusive'), ('non_exclusive', 'Non-Exclusive')], default='non_exclusive', max_length=20)),
                ('assigned_se', models.ForeignKey(blank=True, limit_choices_to={'role': 'se'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_applications_assigned', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='contract_applications', to=settings.AUTH_USER_MODEL)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_application', to='stories.story')),
            ],
            options={
                'db_table': 'contract_applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
