# Generated by Django 6.0.4 on 2026-05-14 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0004_contractapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoreditorlink',
            name='assigned_ae',
        ),
        migrations.AlterField(
            model_name='authoreditorlink',
            name='assigned_se',
            field=models.ForeignKey(blank=True, help_text='The SE who invited or was assigned this author.', limit_choices_to={'role': 'se'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='editorinvite',
            name='role',
            field=models.CharField(choices=[('se', 'Senior Editor')], max_length=5),
        ),
    ]
