# Generated by Django 6.0.4 on 2026-06-11 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0007_announcement_authorwarning_sepromreq_authormessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormessage',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorwarning',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sepromotionrequest',
            name='se',
            field=models.ForeignKey(limit_choices_to={'role': 'se'}, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
