# Generated by Django 6.0.4 on 2026-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0008_alter_authormessage_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message shown across all dashboards.')),
                ('notice_type', models.CharField(choices=[('info', 'Info (blue)'), ('warning', 'Warning (yellow)'), ('error', 'Error/Alert (red)'), ('success', 'Success (green)')], default='info', max_length=10)),
                ('cta_label', models.CharField(blank=True, default='', help_text='Optional button label.', max_length=80)),
                ('cta_url', models.CharField(blank=True, default='', help_text='Optional button URL.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
