# Generated by Django 6.0.4 on 2026-06-26 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0011_promotion_slot_config_story_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotionslotconfig',
            name='unique_category_se_slot',
        ),
        migrations.AlterField(
            model_name='authoreditorlink',
            name='link_method',
            field=models.CharField(choices=[('editor_code', 'Author used editor invite code'), ('manual', 'Manually assigned by CE / admin'), ('auto', 'Auto-assigned by system'), ('author_chosen', 'Author selected during contract application')], default='editor_code', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='promotionslotconfig',
            unique_together={('category', 'se')},
        ),
    ]
