from django.urls import path
from . import views

urlpatterns = [
    path('',                            views.StoryListCreateView.as_view()),
    path('mine/',                       views.MyStoriesView.as_view()),
    path('trending/',                   views.TrendingStoriesView.as_view()),
    path('featured/',                   views.FeaturedStoriesView.as_view()),
    path('editors-pick/',               views.EditorsPickView.as_view()),
    path('completed-stories/',          views.CompletedStoriesView.as_view()),
    path('free-download/',              views.FreeDownloadStoriesView.as_view()),
    path('world-Famous/',               views.WorldFamousStoriesView.as_view()),
    path('african-folktale/',           views.AfricanFolktaleStoriesView.as_view()),
    path('bookmarks/',                  views.MyBookmarksView.as_view()),
    path('genres/',                     views.GenreListView.as_view()),
    path('subgenres/',                  views.SubgenreListView.as_view()),
    path('tags/',                       views.TagListView.as_view()),
    path('banners/',           views.PromoBannersView.as_view(),      name='promo-banners'),
    path('short-stories/',     views.ShortStoriesView.as_view(),      name='short-stories'),
    path('new-arrivals/',      views.NewArrivalsView.as_view(),       name='new-arrivals'),
    path('recommended/',       views.RecommendedForYouView.as_view(), name='recommended'),
    path('free-discount/',     views.FreeDiscountView.as_view(),      name='free-discount'),
    path('rankings/',          views.RankingsView.as_view(),          name='rankings'),
    path('author-spotlight/',  views.AuthorSpotlightView.as_view(),   name='author-spotlight'),
    path('explore-tab/<str:tab>/', views.ExploreTabView.as_view(),   name='explore-tab'),
    path('ranking-section/',       views.RankingSectionView.as_view(),   name='ranking-section'),
    path('genre-section/',         views.GenreTabSectionView.as_view(),  name='genre-section'),
    path('request/',           views.BookRequestView.as_view(),       name='book-request'),
    path('<slug:slug>/',                views.StoryDetailView.as_view()),
    path('<slug:slug>/bookmark/',       views.BookmarkView.as_view()),
    path('<slug:slug>/progress/',       views.UpdateReadingProgressView.as_view()),
    path('<slug:slug>/rate/',           views.RateStoryView.as_view()),
    path('<slug:slug>/characters/',            views.StoryCharactersView.as_view()),
    path('<slug:slug>/characters/<int:pk>/',   views.StoryCharacterDetailView.as_view()),
    path('<slug:slug>/apply-contract/',   views.apply_for_contract),
    path('<slug:slug>/update-calendar/',  views.story_update_calendar),
]