# Generated by Django 6.0.4 on 2026-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'branch_choices',
            },
        ),
        migrations.CreateModel(
            name='BranchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(help_text='The choice question shown to readers', max_length=500)),
                ('position', models.PositiveIntegerField(help_text='Paragraph index where choice appears')),
                ('voting_open', models.BooleanField(default=True)),
                ('voting_ends', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'branch_points',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BranchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'branch_votes',
            },
        ),
    ]
