# Generated by Django 6.0.4 on 2026-04-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branching', '0001_initial'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchchoice',
            name='result_chapter',
            field=models.ForeignKey(blank=True, help_text='Chapter that follows if this choice wins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_sources', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='branchpoint',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_points', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='branchchoice',
            name='branch_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='branching.branchpoint'),
        ),
        migrations.AddField(
            model_name='branchvote',
            name='branch_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branching.branchpoint'),
        ),
        migrations.AddField(
            model_name='branchvote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branching.branchchoice'),
        ),
    ]
