# Generated by Django 6.0.4 on 2026-04-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.story'),
        ),
        migrations.AddField(
            model_name='chapterunlock',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='chapters.chapter'),
        ),
    ]
