# Generated by Django 6.0.4 on 2026-04-25 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0002_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freechapterschedule',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='freechapterschedule',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story'),
        ),
        migrations.AddField(
            model_name='freechapterschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('story', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterunlock',
            unique_together={('user', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='freechapterschedule',
            unique_together={('user', 'story', 'date')},
        ),
    ]
