# Generated by Django 6.0.4 on 2026-05-09 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
