# Generated by Django 6.0.4 on 2026-05-12 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_chapter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='reviewed_by_se',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'se'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='se_reviewed_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='se_note',
            field=models.TextField(blank=True, help_text='SE feedback visible to the author — revision notes or approval message.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_review', 'Pending SE Review'), ('se_reviewing', 'SE Reviewing'), ('se_revision', 'Revision Requested by SE'), ('se_approved', 'SE Approved'), ('contract_sent', 'Contract Sent'), ('contracted', 'Contracted'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
    ]
