# Generated by Django 6.0.4 on 2026-06-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_chapter_reviewed_at_chapter_reviewed_by_se_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
