# Generated by Django 6.0.4 on 2026-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_chapter_edit_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptereditrequest',
            name='se_note',
            field=models.TextField(blank=True, help_text='SE feedback to the author on this edit.'),
        ),
    ]
