# Generated by Django 6.0.4 on 2026-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_alter_chaptereditrequest_se_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptereditrequest',
            name='original_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chaptereditrequest',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
