# Generated by Django 6.0.4 on 2026-08-26 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_chaptereditrequest_original_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterAdAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accesses', to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_chapter_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chapter_ad_accesses',
                'indexes': [models.Index(fields=['user', 'created_at'], name='chapter_ad__user_id_dac7c9_idx')],
            },
        ),
    ]
