# Generated by Django 6.0.4 on 2026-08-26 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_chapteradaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterUnlockEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(help_text="The author's share, credited on release.")),
                ('coins_spent', models.PositiveIntegerField(help_text='What the reader paid, kept for audit.')),
                ('status', models.CharField(choices=[('held', 'Held — awaiting editorial release'), ('released', 'Released to author'), ('rejected', 'Rejected — never paid')], db_index=True, default='held', max_length=10)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_unlock_earnings', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_earnings', to='chapters.chapter')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_chapter_earnings', to=settings.AUTH_USER_MODEL)),
                ('unlock', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning', to='chapters.chapterunlock')),
            ],
            options={
                'db_table': 'chapter_unlock_earnings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', 'status'], name='chapter_unl_author__6ae40d_idx')],
            },
        ),
    ]
