# Generated by Django 6.0.4 on 2026-04-25 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.genre'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers_progress', to='stories.story'),
        ),
        migrations.AddField(
            model_name='rating',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stories.story'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='stories.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'story')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'story')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'story')},
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', 'language'], name='stories_status_2d5723_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['genre', 'status'], name='stories_genre_i_630812_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-total_views'], name='stories_total_v_4d677d_idx'),
        ),
    ]
