# Generated by Django 6.0.4 on 2026-05-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_threshold', models.PositiveSmallIntegerField(default=5, help_text='Number of chapters an author must upload before their first batch enters the SE review queue. Can be overridden per-story.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='review_threshold_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override the global review threshold for this story only. Leave blank to use the platform default.', null=True),
        ),
    ]
