# Generated by Django 6.0.4 on 2026-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_platformsettings_story_review_threshold_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='contract_status',
            field=models.CharField(choices=[('none', 'None'), ('under_review', 'Under Review'), ('contract_sent', 'Contract Sent'), ('signed', 'Signed')], default='none', max_length=20),
        ),
    ]
