# Generated by Django 6.0.4 on 2026-05-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='contract_eligible',
            field=models.BooleanField(default=False, help_text='True when chapter threshold is hit and author can apply for contract.'),
        ),
    ]
