# Generated by Django 6.0.4 on 2026-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_contract_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='review_threshold',
            field=models.PositiveSmallIntegerField(default=6, help_text='Number of chapters an author must upload before their first batch enters the SE review queue. Can be overridden per-story.'),
        ),
    ]
