# Generated by Django 6.0.4 on 2026-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_platformsettings_post_contract_word_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='characters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='target_audience',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='target_word_count',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='post_contract_word_threshold',
            field=models.PositiveIntegerField(default=10000, help_text='Total word count a signed story must reach before it goes live (status → ongoing) and all held chapters are published. e.g. 10000 means the story needs 10 000 words total after signing.'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='review_threshold',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of chapters an author must upload before their first batch enters the SE review queue. Can be overridden per-story.'),
        ),
    ]
