# Generated by Django 6.0.4 on 2026-05-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_target_audience_word_count_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='external_link',
            field=models.URLField(blank=True, default='', help_text='Link to this story on another platform, e.g. Wattpad, AO3.', max_length=500),
        ),
    ]
