# Generated by Django 6.0.4 on 2026-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_story_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='words_at_signing',
            field=models.PositiveIntegerField(default=0, help_text='word_count snapshot taken when contract was signed; used to measure post-contract words only.'),
        ),
    ]
