# Generated by Django 6.0.4 on 2026-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_story_words_at_signing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='contract_status',
            field=models.CharField(choices=[('none', 'None'), ('under_review', 'Under Review'), ('contract_sent', 'Contract Sent'), ('awaiting_signature', 'Awaiting Signature'), ('signed', 'Signed'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
