# Generated by Django 6.0.4 on 2026-06-12 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_story_chapters_per_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='free_until',
            field=models.DateTimeField(blank=True, help_text='If set, the story is temporarily free until this datetime.', null=True),
        ),
        migrations.CreateModel(
            name='FeaturedAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text="Short tagline shown under the author's name.", max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'featured_authors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoryDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('unlocks', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='stories.story')),
            ],
            options={
                'db_table': 'story_daily_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['story', 'date'], name='story_daily_story_i_2614c1_idx')],
                'unique_together': {('story', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserStoryInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('unlocked', models.BooleanField(default=False)),
                ('rated', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_story_interactions',
                'unique_together': {('user', 'story')},
            },
        ),
    ]
