# Generated by Django 6.0.4 on 2026-06-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_home_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='african_folktale_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='editors_pick_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='featured_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='free_download_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='world_famous_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
