# Generated by Django 6.0.4 on 2026-06-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0018_subgenre_tag_genre_story_subgenre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='story',
            name='subgenre',
            field=models.ForeignKey(blank=True, help_text='Optional subgenre. Must belong to the selected genre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.subgenre'),
        ),
        migrations.AlterField(
            model_name='storycoverrequest',
            name='se_note',
            field=models.TextField(blank=True, help_text='SE feedback to the author on this cover change.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='The genre this trope/tag is most associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tropes', to='stories.genre'),
        ),
    ]
