# Generated by Django 6.0.4 on 2026-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_story_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_library_banner',
            field=models.BooleanField(default=False),
        ),
    ]
