# Generated by Django 6.0.4 on 2026-07-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_story_library_banner_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='age_rating',
            field=models.CharField(choices=[('13+', '13+ — Teen'), ('16+', '16+ — Older Teen'), ('18+', '18+ — Mature')], default='13+', help_text='Minimum reader age, declared by the author.', max_length=4),
        ),
        migrations.AddField(
            model_name='story',
            name='is_explicit',
            field=models.BooleanField(default=False, help_text='Author-declared explicit sexual content. Explicit stories are always 18+ and are excluded from store-restricted catalogs (e.g. the iOS app).'),
        ),
    ]
