# Generated by Django 6.0.4 on 2026-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0023_story_age_rating_story_is_explicit'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='show_explicit_content',
            field=models.BooleanField(default=False, help_text='Master switch. When OFF, stories marked explicit are hidden from all public listings, search, story pages and reading endpoints on every platform (app and web). Authors always keep access to their own stories, and editors to their queues.'),
        ),
    ]
