# Generated by Django 6.0.4 on 2026-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_platformsettings_show_explicit_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle OFF to hide this genre and all of its stories from the app and website. Authors keep access to their own stories.'),
        ),
    ]
