# Generated by Django 6.0.4 on 2026-07-17 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_genre_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('sexual', 'Sexual or explicit content'), ('violence', 'Graphic violence'), ('hate', 'Hate speech or harassment'), ('copyright', 'Copyright infringement'), ('spam', 'Spam or misleading'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='stories.story')),
            ],
            options={
                'db_table': 'content_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
