from django.urls import path
from . import views

app_name = 'editorial'

urlpatterns = [
    # Story-level SE review (primary flow)
    path('story-queue/', views.SEStoryQueueView.as_view(), name='story-queue'),
    path('story-queue/<slug:slug>/', views.SEStoryDetailView.as_view(), name='story-detail'),
    path('story-queue/<slug:slug>/approve/', views.se_approve_story, name='story-approve'),
    path('story-queue/<slug:slug>/reject/', views.se_reject_story, name='story-reject'),
    path('story-queue/<slug:slug>/reopen/', views.se_reopen_story, name='story-reopen'),
    path('story-queue/<slug:slug>/escalate/', views.se_escalate_story_to_ce, name='story-escalate'),
    path('story-queue/<slug:slug>/mark-complete/', views.se_mark_story_complete, name='story-mark-complete'),
    path('story-queue/<slug:slug>/set-lock/', views.se_set_lock_chapter, name='story-set-lock'),
    path('story-queue/<slug:slug>/panel/', views.se_story_panel, name='story-panel'),
    path('story-queue/<slug:slug>/edit/', views.se_edit_story, name='se-story-edit'),
    path('chapters/<int:pk>/edit/', views.se_edit_chapter, name='se-chapter-edit'),
    path('my-stories/', views.se_my_stories, name='se-my-stories'),
    path('flags/', views.se_my_flags, name='se-my-flags'),
    path('flags/submit/', views.se_submit_flag, name='se-submit-flag'),
    path('promotion-requests/', views.se_promotion_requests, name='se-promotion-requests'),
    path('author-balances/', views.se_author_balances, name='se-author-balances'),
    path('author-balance/<int:author_id>/approve/', views.se_approve_author_balance, name='se-approve-balance'),
    path('author-balance/<int:author_id>/award-bonus/', views.se_award_completion_bonus, name='se-award-bonus'),
    # CE story review
    path('ce-story-queue/', views.CEStoryQueueView.as_view(), name='ce-story-queue'),
    path('ce-story-queue/<slug:slug>/', views.CEStoryDetailView.as_view(), name='ce-story-detail'),
    path('ce-story-queue/<slug:slug>/send-contract/', views.ce_send_contract_story, name='ce-send-contract-story'),
    path('ce-story-queue/<slug:slug>/reject/', views.ce_reject_story, name='ce-reject-story'),
    path('ce-story-queue/<slug:slug>/note/', views.ce_edit_story_note, name='ce-story-note'),
    path('ce-story-queue/<slug:slug>/ce-sign/', views.ce_editorial_sign, name='ce-editorial-sign'),
    path('ce-story-queue/<slug:slug>/edit/', views.ce_edit_story, name='ce-story-edit'),
    path('ce-story-queue/<slug:slug>/push/', views.ce_story_push, name='ce-story-push'),
    path('assign-author/', views.assign_author_to_se, name='assign-author'),
    path('kyc/',                    views.SEKYCListView.as_view(),  name='se-kyc-list'),
    path('kyc/<int:pk>/se-review/', views.se_review_kyc,           name='se-kyc-review'),
    path('kyc/<int:pk>/review/',    views.ce_review_kyc,           name='ce-review-kyc'),
    # Chapter-level queue (kept for legacy)
    path('queue/', views.EditorialQueueView.as_view(), name='queue'),
    path('reviews/<int:pk>/', views.EditorialChapterDetailView.as_view(), name='review-detail'),
    path('reviews/<int:pk>/approve/', views.se_approve, name='se-approve'),
    path('reviews/<int:pk>/request-revision/', views.se_request_revision, name='se-request-revision'),
    path('reviews/<int:pk>/remove/', views.se_remove_content, name='se-remove'),
    path('reviews/<int:pk>/escalate-to-ce/', views.se_escalate_to_ce, name='se-escalate-to-ce'),
    path('ce-escalations/', views.CEEscalationsView.as_view(), name='ce-escalations'),
    path('reviews/<int:pk>/ce-approve/', views.ce_send_contract, name='ce-send-contract'),
    path('contracts/accept/', views.accept_contract, name='accept-contract'),
    path('contracts/decline/', views.decline_contract, name='decline-contract'),
    path('assignments/', views.EditorAssignmentListCreateView.as_view(), name='assignments'),
    path('author-links/', views.AuthorEditorLinkListCreateView.as_view(), name='author-links'),
    path('team/', views.EditorialTeamView.as_view(), name='team'),
    path('stats/', views.EditorialStatsView.as_view(), name='stats'),
    path('validate-code/', views.validate_editor_code, name='validate-code'),
    path('link-editor/', views.link_editor_by_code, name='link-editor'),
    path('my-editor/', views.my_editor_link, name='my-editor'),
    path('my-code/', views.my_editor_code, name='my-code'),
    path('invites/', views.invite_list, name='invite-list'),
    path('invites/<int:pk>/revoke/', views.invite_revoke, name='invite-revoke'),
    path('invites/<int:pk>/resend/', views.invite_resend, name='invite-resend'),
    # CE account moderation
    path('ce/suspicious-accounts/', views.CESuspiciousAccountsView.as_view(), name='ce-suspicious-accounts'),
    path('ce/ip-accounts/<str:ip>/', views.CEIPAccountsView.as_view(), name='ce-ip-accounts'),
    path('ce/device-accounts/<str:device_id>/', views.CEDeviceAccountsView.as_view(), name='ce-device-accounts'),
    path('ce/users/', views.CEUserSearchView.as_view(), name='ce-user-search'),
    path('ce/users/<int:pk>/ban/', views.ce_ban_user, name='ce-ban-user'),
    path('ce/users/<int:pk>/unban/', views.ce_unban_user, name='ce-unban-user'),
    path('ce/users/<int:pk>/disable/', views.ce_disable_user, name='ce-disable-user'),
    path('ce/users/<int:pk>/enable/', views.ce_enable_user, name='ce-enable-user'),
    path('ce/blacklisted-ips/', views.CEBlacklistedIPListView.as_view(), name='ce-blacklisted-ips'),
    path('ce/blacklisted-ips/<int:pk>/', views.ce_remove_blacklisted_ip, name='ce-remove-blacklisted-ip'),
    # CE extended dashboard features
    path('ce/dashboard-stats/', views.CEDashboardStatsView.as_view(), name='ce-dashboard-stats'),
    path('ce/se-performance/', views.CESEPerformanceView.as_view(), name='ce-se-performance'),
    path('ce/books/', views.CEBooksView.as_view(), name='ce-books'),
    path('ce/books/<slug:slug>/remove/', views.ce_remove_story, name='ce-remove-story'),
    path('ce/books/<slug:slug>/restore/', views.ce_restore_story, name='ce-restore-story'),
    path('ce/contracts/', views.CEContractsView.as_view(), name='ce-contracts'),
    path('ce/revenue/', views.CERevenueView.as_view(), name='ce-revenue'),
    path('ce/author-balances/', views.CEAuthorBalancesView.as_view(), name='ce-author-balances'),
    path('ce/payouts/<int:pk>/process/', views.ce_process_payout, name='ce-payout-process'),
    path('ce/payouts/<int:pk>/reject/', views.ce_reject_payout, name='ce-payout-reject'),
    path('ce/analytics/', views.CEAnalyticsView.as_view(), name='ce-analytics'),
    path('ce/flags/', views.CEContentFlagsView.as_view(), name='ce-flags'),
    path('ce/flags/<int:pk>/resolve/', views.ce_resolve_flag, name='ce-flag-resolve'),
    path('ce/warnings/', views.CEAuthorWarningsView.as_view(), name='ce-warnings'),
    path('ce/warnings/<int:pk>/', views.ce_dismiss_warning, name='ce-warning-dismiss'),
    path('ce/authors/<int:author_id>/reassign/', views.ce_reassign_author, name='ce-reassign-author'),
    path('ce/messages/', views.CEAuthorMessagesView.as_view(), name='ce-messages'),
    path('ce/messages/<int:pk>/reply/', views.ce_reply_message, name='ce-message-reply'),
    path('ce/messages/<int:pk>/read/', views.ce_mark_message_read, name='ce-message-read'),
    path('ce/announcements/', views.CEAnnouncementsView.as_view(), name='ce-announcements'),
    path('ce/promotion-requests/', views.CESEPromotionRequestsView.as_view(), name='ce-promotion-requests'),
    path('ce/promotion-requests/<int:pk>/review/', views.ce_review_promotion, name='ce-promotion-review'),
    path('ce/tab-pins/', views.CETabPinsView.as_view(), name='ce-tab-pins'),
    path('ce/tab-pins/<int:pk>/', views.ce_tab_pin_detail, name='ce-tab-pin-detail'),
    # SE directory — for authors to browse/select an SE at contract time
    path('se-list/', views.se_list, name='se-list'),
    # SE chapter edit + cover change review
    path('chapter-edits/',                    views.SEChapterEditQueueView.as_view(),  name='se-chapter-edit-queue'),
    path('chapter-edits/<int:pk>/review/',    views.se_review_chapter_edit,           name='se-chapter-edit-review'),
    path('cover-requests/',                   views.SECoverRequestQueueView.as_view(), name='se-cover-request-queue'),
    path('cover-requests/<int:pk>/review/',   views.se_review_cover_request,          name='se-cover-request-review'),
    # SE promotion slot management
    path('promotions/', views.SEPromotionListCreateView.as_view(), name='se-promotions'),
    path('promotions/<int:pk>/', views.se_remove_promotion, name='se-promotion-remove'),
    # CE promotion oversight + slot config
    path('ce/promotions/', views.CEPromotionListView.as_view(), name='ce-promotions'),
    path('ce/promotions/<int:pk>/', views.ce_remove_promotion, name='ce-promotion-remove'),
    path('ce/slot-configs/', views.CESlotConfigView.as_view(), name='ce-slot-configs'),
    # Author-facing & system
    path('announcements/', views.author_announcements, name='author-announcements'),
    path('system-notice/', views.system_notice, name='system-notice'),
]