# Generated by Django 6.0.4 on 2026-06-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='audience',
            field=models.CharField(choices=[('public', 'Everyone'), ('authors', 'Authors only')], default='public', help_text='Who can read this article', max_length=10),
        ),
    ]
