# Generated by Django 6.0.4 on 2026-04-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochapter',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='audiolistenhistory',
            name='audio_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audiochapter'),
        ),
    ]
