# Generated by Django 6.0.4 on 2026-05-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique invite code for AEs to share with authors.', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('admin', 'Admin'), ('ae', 'Assistant Editor'), ('se', 'Senior Editor'), ('ce', 'Chief Editor')], default='reader', max_length=10),
        ),
    ]
