# Generated by Django 6.0.4 on 2026-05-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_editor_code_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='contract_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the author accepted the contract.', null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='has_contract',
            field=models.BooleanField(default=False, help_text='True once the author has signed a contract with the platform. Chapters bypass SE review and are published immediately.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='editor_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique invite code for AEs/SEs to share with authors.', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('admin', 'Admin'), ('ae', 'Acquisition Editor'), ('se', 'Senior Editor'), ('ce', 'Chief Editor')], default='reader', max_length=10),
        ),
    ]
