# Generated by Django 6.0.4 on 2026-06-15 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_registration_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='balance_approved_at',
            field=models.DateTimeField(blank=True, help_text='When an SE last approved this balance for the current month.', null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='balance_approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'se'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_author_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus_balance',
            field=models.PositiveIntegerField(default=0, help_text='Coins earned from rewards (checkin, ads, reading). Spent before paid coins.'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('bonus', 'Bonus Reward')], max_length=6),
        ),
    ]
