# Generated by Django 6.0.4 on 2026-07-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_author_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_free_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='audiobook_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
