# Generated by Django 6.0.4 on 2026-08-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_ad_free_audiobook_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Collected at signup (or backfilled post-login for legacy and social-login accounts). Write-once via the API.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restricted_mode_enabled',
            field=models.BooleanField(default=False, help_text='Opt-in parental control: hides 18+/explicit content on this account regardless of age. Locked behind a PIN.'),
        ),
        migrations.AddField(
            model_name='user',
            name='restricted_mode_pin',
            field=models.CharField(blank=True, help_text='Hashed via make_password — never store the raw PIN.', max_length=128),
        ),
    ]
