# Generated by Django 6.0.4 on 2026-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coins_total', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payout_method', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author_payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('coins', models.PositiveIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bonus_coins', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coin_packages',
                'ordering': ['price_usd'],
            },
        ),
        migrations.CreateModel(
            name='DailyRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('checkin', 'Daily Check-in'), ('reading_5', 'Reading 5 min'), ('reading_10', 'Reading 10 min'), ('reading_30', 'Reading 30 min'), ('reading_60', 'Reading 60 min'), ('reading_120', 'Reading 120 min'), ('reading_180', 'Reading 180 min'), ('ad', 'Watch Ad'), ('signin', 'Sign In Reward'), ('notification', 'Notification Reward')], max_length=50)),
                ('coins', models.IntegerField()),
                ('claimed_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('coin_pack', 'Coin Pack'), ('subscription', 'Subscription')], max_length=15)),
                ('coins_granted', models.PositiveIntegerField(default=0)),
                ('amount_paid_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=200)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('chapter_title', models.CharField(blank=True, default='', max_length=300)),
                ('read_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reading history',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('hour', models.IntegerField(default=21)),
                ('minute', models.IntegerField(default=0)),
                ('days', models.JSONField(default=list)),
                ('goal_minutes', models.IntegerField(default=30)),
                ('goal_reminder', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=1)),
                ('minutes', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_sub_id', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coins_per_month', models.PositiveIntegerField()),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
    ]
