# Generated by Django 6.0.4 on 2026-07-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_checkin_streak_task_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon, e.g. 📖', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='Can a user complete this more than once?'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='response',
            field=models.TextField(blank=True, help_text='User-submitted text for response-type tasks'),
        ),
    ]
