# Generated by Django 6.0.4 on 2026-07-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagevisit',
            new_name='page_visits_created_b3088b_idx',
            old_name='pv_created_country_idx',
        ),
        migrations.RenameIndex(
            model_name='pagevisit',
            new_name='page_visits_created_bcffaa_idx',
            old_name='pv_created_device_idx',
        ),
    ]
