# Generated by Django 6.0.4 on 2026-04-25 14:47

import novelux_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='e.g. 1.0.0', max_length=20, unique=True)),
                ('version_code', models.PositiveIntegerField(help_text='Integer build number, must increase each release', unique=True)),
                ('apk_file', models.FileField(help_text='Upload the .apk file here', upload_to=novelux_web.models.apk_upload_path)),
                ('release_notes', models.TextField(blank=True, help_text='What changed in this version (shown on download page)')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active release is served to users')),
                ('min_android', models.CharField(default='8.0', help_text='Minimum Android version required', max_length=10)),
                ('size_mb', models.DecimalField(blank=True, decimal_places=1, help_text='Leave blank — auto-calculated on save', max_digits=6, null=True)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apk_releases',
                'ordering': ['-version_code'],
            },
        ),
    ]
