# Generated by Django 6.0.4 on 2026-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS')], default='Android', max_length=10)),
                ('device_model', models.CharField(blank=True, default='', max_length=200)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_chapter', 'New Chapter'), ('tip_received', 'Tip Received'), ('new_follower', 'New Follower'), ('comment_reply', 'Comment Reply'), ('comment_like', 'Comment Like'), ('vote_result', 'Vote Result'), ('bonus_earned', 'Bonus Earned'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra payload: {"screen": "story", "slug": "..."}')),
                ('image_url', models.URLField(blank=True, default='')),
                ('audience', models.CharField(choices=[('all', 'All users'), ('user', 'Specific user'), ('platform', 'By platform (Android/iOS)'), ('genre', 'By genre preference')], default='all', max_length=20)),
                ('platform', models.CharField(blank=True, default='', help_text='Android or iOS — leave blank for all', max_length=10)),
                ('genre_slug', models.CharField(blank=True, default='', help_text='Filter by preferred genre if audience=genre', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('partial', 'Partially sent')], default='pending', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
